# Site Settings
baseurl: ""
url : "https://iampdm.com"

# Blog Settings
theme_settings :
  title : IamPdm.com
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Vladimir Ovsyanikov
    description : Product Manager at Cloudcall (SAFe POPM, CSPO, CSM)
    experience :
      - start : 2018-02-01
        experience : Cloudcall, Product Manager

    skills : 
      - skill : Product Managment
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: naye0ng
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
